apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: | 
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
        listen       80;
        server_name  localhost;
        error_log  /var/log/nginx/error.log  debug;
        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
               auth_basic           "u shall not pass";
          auth_basic_user_file /etc/htpasswd/htpasswd;
        }
      }
    }
